name: ${project.name}
main: com.github.maxopoly.finale.Finale
author: Maxopoly
version: ${project.version}
depend: [CivModCore]
softdepend: [CombatTagPlus]
commands:
    finalereload:
        permission: finale.op
        aliases: [reloadfinale]
    cps:
        description: Show CPS.
        permission: finale.cps
    combatconfig:
        description: View/modify combat config values.
        permission: finale.cmv
    finalegive:
        description: Give finale custom items.
        permission: finale.give
permissions:
    finale.op:
        default: op
    finale.cps:
        default: op
    finale.cmv:
        default: op
    finale.give:
        default: op